variables:
  projectname: project_management
  version: 0.0.1-SNAPSHOT
  projectuser: admin
  projectpath: /project_management

stages:
  - build
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - mvn clean install -DskipTests=true
  tags:
    - livesvbao

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - sudo cp target/$projectname-$version.jar $projectpath
    - sudo chown -R $projectuser. $projectpath
    - sudo -u $projectuser nohup java -jar $projectpath/$projectname-$version.jar > nohup.out 2>&1 &
  tags:
    - livesvbao
